---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-vip-daemonset.yaml
  - rbac-secret.sops.yaml
  - rbac.yaml
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: disabled
