---
creation_rules:
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age100tc6lnl96420a8tm65g0cdje80uec74pjpsnurkl8yy5lyjefkssuelru
  - path_regex: cluster/.*\.sops\.ini
    key_groups:
      - age:
          - age100tc6lnl96420a8tm65g0cdje80uec74pjpsnurkl8yy5lyjefkssuelru
  - path_regex: cluster/.*\.sops\.toml
    key_groups:
      - age:
          - age100tc6lnl96420a8tm65g0cdje80uec74pjpsnurkl8yy5lyjefkssuelru
