apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PROSOC_DOMAIN: ENC[AES256_GCM,data:iVyoFn5vzV1qCUJHhq3bH8Q=,iv:0ojVfh/J48W+q+lcJhv1rNiBOTiBxwuG2HeWgOCJybQ=,tag:a1ZIC2ykYbOzPh9zHxF5Hw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:pBxTcAvlBmcwRir76Zfk4P2krN4=,iv:nRvjPKQHo9Nd/JbKjSN9/qDgNrqukiKp4H80shZ3bCA=,tag:xqXgFm8N74o+pNIc2hKukg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pll58t9vdaw5q0nh89mfxjdu099jyh5dkr9m5gy46fwyr5w25upqs8sfge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMW8yMVhMNHJ0d3JDMjFp
            TE5VaWlRRWdiSHo5NmdlOEdqYWM3N1dSNHkwClVWREd1c0Rscyt3ZWExT0xMMmhI
            L3EyQkJJOGNuVXlHVWlGVW4waXNHU1EKLS0tIHZyRDVxaW5vcXRlem1uY29vVW1L
            bDZCbzlLL0hBbkJ5aERMQUYzTG1XVDAKNDIWCcjVPXXDylspREYmVyVVqRbb5Zqs
            Y0Yjl1qft9NaqRiB3PbYQ/tNbO57LGCipzMUeh9D7gZjHsmCooDoTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T21:29:15Z"
    mac: ENC[AES256_GCM,data:WcHlcqL02HLoOP06/v8bFg212JZKCm0MhZgzXeVqX+cK9xvimwShtfl3WgjKcjZCHCO8+pK4dQkksBAggLbkAwVcZXr+Rzd8UuBCtMF9ACc93IJNLuDHetgP7b38Bk643HZQ93j9jXBxuKhOPX1wOfsJJ7S2gOfYyz/IQqlTv38=,iv:9S6yyhqevGrAYmt4AbSkseescOn4T3z8MuQLocnTz1g=,tag:YJmyeDhCkEZIZB/WR63o/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
