---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: master
  url: https://github.com/jaken1986/demo-day.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
