---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name gitea
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
