---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: gitea
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      rootless: true
    containerSecurityContext:
      capabilities:
        add:
          - SYS_CHROOT
    ingress:
      enabled: true
      hosts:
        - host: &host "gitea.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    memcached:
      enabled: false
    postgresql:
      enabled: false
    persistence:
      enabled: true
      existingClaim: gitea-config-v1
    signing:
      enabled: true
      gpgHome: /data/git/.gnupg
    gitea:
      admin:
        email: "gitea@${SECRET_DOMAIN}"
        username: gitea
      config:
        APP_NAME: Tea, Git, Hot
        server:
          DISABLE_SSH: true
          DOMAIN: "gitea.${SECRET_DOMAIN}"
          ROOT_URL: "https://gitea.${SECRET_DOMAIN}"
          ENABLE_GZIP: true
          LANDING_PAGE: login
          LFS_START_SERVER: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        ui:
          DEFAULT_THEME: arc-green
        repository:
          DEFAULT_BRANCH: main
          DEFAULT_PRIVATE: true
        database:
          DB_TYPE: sqlite3
        service:
          DISABLE_REGISTRATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
          REQUIRE_SIGNIN_VIEW: true
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          DEFAULT_ALLOW_CREATE_ORGANIZATION: false
          DEFAULT_USER_IS_RESTRICTED: true
        cron:
          ENABLED: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: gitea-config
  valuesFrom:
    - targetPath: gitea.admin.password
      kind: Secret
      name: gitea-config
      valuesKey: adminPassword
