kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gitea-config
    namespace: default
stringData:
    adminPassword: ENC[AES256_GCM,data:ezNDs9E=,iv:2DE/6lA2YF/wMAtZte3cRRHBIPdPGteoZvHxDX3W8Ek=,tag:uIR1zI/T/BYd0BiyafMq2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age100tc6lnl96420a8tm65g0cdje80uec74pjpsnurkl8yy5lyjefkssuelru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbno5ckt5VGFCZm1KSXAw
            clFTanFpUnkrZ3M5SElDSUZsUkFJZnltSVJVCk9TZXZIcGZhL3o0OWIxMHhFMUFX
            QVlCWTNKMzE1WTBMOVVFWDAySWNPWUkKLS0tIGhHZWNwcW0rTTd6Q1BXRnRNd3Zr
            b2RHOHlVb3poaFBOR0lVOW9tYmJQWlUKLAMAkNd1NsPUrVGjd2pSQDAFNIYs3H+d
            IenSSw1lCE30QkOSUNL2NuqTzCBGmDhh1RVCpJbsi0JFF8pIfZ5JMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-22T01:48:44Z"
    mac: ENC[AES256_GCM,data:Cq6LcIWdr+a+EsEtBh5gjMYTT2deTL3TUdzLJ1qZYTu+c2/ZkIXgHZxw0hAXD7Bxt6Pq1QXxLRCu9hFhIm25Ma3GumOHk95AKlKj7eurNu4I6TPtfAvd4+/TjzXHJ95lKBfSPE3wd9iVD+9QpkNHQvoyH1B7BHg2XZURLY1tWyk=,iv:PbFZTsJe1jfUqJUqfdB7IdVYoY92ZipW0q08gV0ikWk=,tag:QXAHVYWdmDAQEmX6N+L6OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
