---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dynu-webhook
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: dynu-webhook
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-dynu-webhook
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    groupName: ${SECRET_DOMAIN}
    certManager:
      namespace: kube-system
