---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/elastic-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: apps
