---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=docker image=docker.elastic.co/eck/eck-operator
  - https://download.elastic.co/downloads/eck/2.4.0/crds.yaml
