---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elastic-stack
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`kibana.${SECRET_DOMAIN}`)"
      kind: Rule
      services:
        - name: elastic-kibana-kb-http
          port: 5601
          scheme: https
